version: '3.8'

services:

  postgres-dev-db:
    image: postgres:16.3-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: dev_apphostalpaly
    volumes:
      - ./containers/dev/postgres:/var/lib/postgresql/data
    ports:
      - ${DB_PORT_DOCKER}:${DB_PORT_POSTGRES}
